### ISSUE TITLE
Small framework idea

### ISSUE THREAD

**Issue by zeffii** [zeffii/SoundPetal#1]
For now this is experimental. The idea is to start with numpy as a basis for data-sockets. Some nodes will be dict aware and can easily ask and get objects. The main carrier socket for unspecialized geometry is `FlowArraySocket`. Geometry can be packed into object bundles and will travel onwards through `FlowGeometrySocket` to the viewer Node.

Nodes to implement: (btw, there are more modes than these but some are testing only)

Repr
- [ ] | bgl viewer | draws geometry using 'fast' cached bgl draw list in 3d view
- [x] | bmesh viewer | generates bmesh on the fly using `bmesh.from_py_data` 
- [x] | filter mesh | show for a mesh object_collection the `v,e,f` of each member object

Make
- [x]  |  np A range | makes float range arrays
- [x]  | UVEdgeSurf | given a vertex mesh, generates edges + faces / cyclic u + v

Do
- [ ] | Scripted | process() of node is defined by a 'hot loaded' script.
- [ ] | REPL | live REPL from node UI

Ops
- [x] | Verts Transform | translate, scale, rotate
- [x] | Scalar Math | Scalar math on arrays, actually can do Vector Math too... bad name

Repr
- [ ]  | bgl Repr     | Visual stethoscope for the node view, draw content in nodeview
- [x] | debug print | Show print statements to stdout

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/4618900/e00ba6bc-530e-11e4-935e-0c9ea7f61516.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/4631962/bd67adb2-53b9-11e4-934b-f1f2f48fe4c2.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/4643896/7a5bf64a-5454-11e4-8610-ff2bbef735b8.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/4644391/604fa5ac-545a-11e4-9165-f8962f275d59.png)

**Comment by ly29** [comment]
This looks far more promising long term than Sverchok.

**Comment by zeffii** [comment]
The implementation is quite brittle (even verbose) for now, I want to see how things work. About to try out a Matrix Transform node.

Loving the numpy tho, even if i'm not using the fastest syntax yet.

**Comment by zeffii** [comment]
implemented scale and translate, rotate not tried yet.. probably need W to be 1 for affine rotate

**Comment by zeffii** [comment]
woah: http://stackoverflow.com/a/12261243/1243487

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/4661151/27ff8eda-5520-11e4-9b66-3904dbdb018e.png)

**Comment by zeffii** [comment]
an old favourite, petal sine.
![image](https://cloud.githubusercontent.com/assets/619340/4661285/b40ab0de-5521-11e4-9a85-8deb628fed99.png)

**Comment by zeffii** [comment]
- should really work at getting draw labels working, spacesaver++
- must implement cache cleanup on node delete.

**Comment by zeffii** [comment]
@ly29 did you know about this `.enabled` behaviour for sockets? magic.
![magic_feature](https://cloud.githubusercontent.com/assets/619340/4663695/db561c2a-553d-11e4-9907-c651e491343f.gif)

**Comment by ly29** [comment]
That looks really cool.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/4667454/23d35020-555d-11e4-8052-e56cc65c19f5.png)
The layout language is a little rigid in these cases

**Comment by zeffii** [comment]
added new nodes and operator to show console on stdout node

**Comment by zeffii** [comment]
scalar math node ~~needs~~ to handle on UI values ~~too, currently only external input~~
