### ISSUE TITLE
short term issues to solve

### ISSUE THREAD

**Issue by zeffii** [zeffii/SoundPetal#2]
Milestone 1  `0.1`
- [x] F8 refresh existing nodes
- [x] subclass sockets
- [x] prop_name or slider
- [x] [make a few nodes to allow experimentation](https://github.com/zeffii/FLOW/issues/1).
- [x] build dependency graph, or use ng.links
- [x] implement `=updateSD`  (Self and Downstream)
- [x] renamed socket bl_idname, now  Flow` prefixes all.
- [x] imports all start with FLOW now ( redux namespace polution )

**Comment by ly29** [comment]
I suggest stop using `update(self)` on node level and instead catching it the tree level where you can compile the node network into something that you can execute/interpret.

**Comment by JacquesLucke** [comment]
This is what I did in animation nodes.
The Performance is awesome

**Comment by zeffii** [comment]
Yep, that was the plan. This won't be exciting for a while (or maybe ever!), I recommend you ignore this repo

**Comment by JacquesLucke** [comment]
Ok :D

**Comment by ly29** [comment]
Re coexistance, this largely a namespace issue.

Things I would do diffrently from sverchok. Have socket names to have names with Flow prefiix. Avoid adding the addon path to the python system path.

**Comment by zeffii** [comment]
cool.. i'll do prefixes and avoid adding to python path.. (not really sure why that is necessary anyway)

**Comment by zeffii** [comment]
As a result of removing FLOW from pythonpath, I now import everything from 

``` python
from FLOW.core
from FLOW.node_tree
```

Something feels better about this explicit statement, it shows where the import is coming from

**Comment by zeffii** [comment]
renamed sockets with prefix

**Comment by zeffii** [comment]
coexistance is now facilitated. good call @ly29

**Comment by zeffii** [comment]
debugging UVEdgeSurf node using Sverchok IndexViewer :) 
![image](https://cloud.githubusercontent.com/assets/619340/4690146/fbd787fa-56db-11e4-921f-0c1e8e3b7a74.png)

**Comment by ly29** [comment]
@zeffii 
I will take deeper look after bcon but this feels much better so far.

**Comment by zeffii** [comment]
todo: do full cascading nodetree update upon F8, current state makes debugging too time consuming.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/4725640/5222f28a-595b-11e4-9291-5af5bd1afd2b.png)
